;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-slash
        counsel-yank-pop
        downcase-region
        evil-backward-char
        evil-backward-word-begin
        evil-find-char
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-insert-line
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-undo
        id/cursors-hydra-keymap/body
        org-delete-char
        org-end-of-line
        org-self-insert-command
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-semicolon
        upcase-region
        wdired-finish-edit
        wgrep-finish-edit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        id/cursors-hydra-keymap/mc/edit-lines-and-exit
        id/cursors-hydra-keymap/mc/mark-all-like-this-and-exit
        id/cursors-hydra-keymap/mc/mark-next-like-this
        id/cursors-hydra-keymap/mc/skip-to-next-like-this
        id/cursors-hydra-keymap/mc/unmark-next-like-this
        ))
